# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_llvm_rcpp_hello_world`)
}

trunc <- function(from, x, to) {
    .Call(`_llvm_trunc_`, from, x, to)
}

lshr <- function(type, x, y) {
    .Call(`_llvm_lshr`, type, x, y)
}

ashr <- function(type, x, y) {
    .Call(`_llvm_ashr`, type, x, y)
}

shl <- function(type, x, y) {
    .Call(`_llvm_shl`, type, x, y)
}

and <- function(x, y) {
    .Call(`_llvm_and_`, x, y)
}

or <- function(x, y) {
    .Call(`_llvm_or_`, x, y)
}

xor <- function(x, y) {
    .Call(`_llvm_xor_`, x, y)
}

fptosi <- function(from, x, to) {
    .Call(`_llvm_fptosi`, from, x, to)
}

fptoui <- function(from, x, to) {
    .Call(`_llvm_fptoui`, from, x, to)
}

uitofp <- function(from, x, to) {
    .Call(`_llvm_uitofp`, from, x, to)
}

sitofp <- function(from, x, to) {
    .Call(`_llvm_sitofp`, from, x, to)
}

sext <- function(from, x, to) {
    .Call(`_llvm_sext`, from, x, to)
}

inc <- function() {
    .Call(`_llvm_inc`)
}

my_norm <- function(mean, sd) {
    .Call(`_llvm_my_norm`, mean, sd)
}

store <- function(name, object) {
    invisible(.Call(`_llvm_store`, name, object))
}

load <- function(name) {
    .Call(`_llvm_load`, name)
}

rcpp_package_function <- function(m) {
    .Call(`_llvm_rcpp_package_function`, m)
}

rcpp_type <- function(x) {
    invisible(.Call(`_llvm_rcpp_type`, x))
}

say_hello <- function(x) {
    .Call(`_llvm_say_hello`, x)
}

