---
title: "Power Harvesting Kit"
subtitle: "This is the subtitle"
author: ferhat erata
date: 14.03.2021
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# output: slidy_presentation
```
<!-- put off-time graphics here -->

<!-- put harvesting kit's charge/discharge graphics here -->

```{r title, echo = FALSE, message = FALSE, results='asis'}

rm(list = ls(all.names = TRUE)) #will clear all objects includes hidden objects.
options("StartupBanner" = "off")
library(distr)
distroptions("WarningArith" = FALSE)
options(scipen = 999)
set.seed(100)
library(pander)

# (1000uF) 1000 x 10^-3 mF; 1mF = 1 x 10^-3 = 0.001 F
# (50mF) 50 x 10^-3 F = 0.05 F
BOOTSTRAP_COUNT <- 10000
V_MAX <- 1.25
V_MIN <- 1.02

capacitances <- c(0.001) # F
distances <- c(60, 70, 80) # cm

for (cap in capacitances) {
  pandoc.header(paste0(cap * 1000, "mF capacitor."), level = 1)
  means <- vector()
  errors <- vector()
  lower <- vector()
  higher <- vector()
  for (d in distances) {
    pandoc.header(paste0(d, "cm ", "for ", cap * 1000, "mF capacitor."), level = 2)
    samples <- vector()
    for (i in 1:10) {
      # file <- paste0("/home/ferhat/git/analysis-framework-standalone-application/experiments/harvester-kit/ten-samples/", d, "cm_10_samples")
      file <- paste0("/home/gokcin/CLionProjects/analysis-framework-standalone-application/experiments/harvester-kit/crc-harvester-energy/", d, "cm_crc_1mF_harvester_energy_profile")
      trace <- read.csv(paste0(file, ".csv"), header = TRUE, sep = ",")
      trace <- subset(trace, select = c(paste0("x", d, "cm_sample_", i, "_time.ms."),
                                        paste0("x", d, "cm_sample_", i, "_power.watt.")))
      row_sub <- apply(trace, 1, function(row) all(row != 0)) # remove rows with 0
      trace <- subset(trace, row_sub)
      names(trace) <- list("Time.ms.", "Power.Watt.")

      time <- as.double(trace$Time.ms.) / 1000 # ms to s
      power <- as.double(trace$Power.Watt.) # watt

      max <- 1 / 2 * cap * V_MAX^2 # j
      min <- 1 / 2 * cap * V_MIN^2 # j
      max <- max - min
      # To REVIEW
      # out_file <- paste0(file, ".", i, ".out.csv")
      # cat(file = out_file, sep = ",", "Time.s", "Voltage.V", "Power.Watt", "Energy.J\n")

      # max(w_1, w_2) * dt - (dw x dt/2)
      t1 <- 0
      w1 <- 0
      e1 <- 0
      e <- 0
      time_stamps <- list(0)
      for (i in seq_along(time)) {
       # v <- voltage[i]
        t2 <- time[i]
        w2 <- power[i]
        dt <- abs(t1 - t2)
        dw <- abs(w1 - w2)
        e2 <- max(w1, w2) * dt - dw * dt / 2
        # To REVIEW
        # cat(file = out_file, append = TRUE, sep = ",", t2, v, w2, paste0(e1 + e2, "\n"))
        e <- e + e2
        if (e > max) {
          e <- 0
          time_stamps <- append(time_stamps, t2)
        }
        t1 <- t2
        w1 <- w2
        e1 <- e1 + e2
      }

      if (length(time_stamps) == 1) {
        # warning("sampling time interval is not enough to model this capacitor size!")
        next
      }

      time_intervals <- vector()
      for (i in 1:(length(time_stamps) - 1)) {
        time_intervals <- append(time_intervals, (time_stamps[[i + 1]] - time_stamps[[i]]) * 1000) # s -> ms
      }
      x_bar <- mean(time_intervals)
      samples <- append(samples, x_bar)

      # To REVIEW
      # trace <- read.csv(out_file, header = TRUE, sep = ",")
      # plot(as.double(trace$Time.s), as.double(trace$Energy.J), type = "l", lty = 1)
    }

    bootstrap_dist <- vector()
    n <- length(samples)
    if (n < 2) {
      # warning("There is not enough sample to make statistical inference!")
      pandoc.p("There is not enough sample to make statistical inference!\nSampling time interval may not be enough to model this capacitor size!")
      means <- append(means, NA)
      errors <- append(errors, NA)
      lower <- append(lower, NA)
      higher <- append(higher, NA)
    } else {
      Ex_bar <- mean(samples)
      for (j in 1:BOOTSTRAP_COUNT) {
        bootstrap_dist <- append(bootstrap_dist, (mean(sample(samples, n, replace = TRUE))))
      }
      se <- sd(bootstrap_dist) # se (standard error) is sd of sampling distribution
      mb <- mean(bootstrap_dist) # mean of the boot would be similar to sample mean

      # inference of the population distribution
      population_distr <- distr::Norm(round(Ex_bar, 2), round(se, 2))
      distr::plot(population_distr, to.draw.arg = "d", bty = "7",
                  panel.first = grid(lwd = 1), lwd = 1, vertical = FALSE, xlab = "ms",
                  col.points = c("red", "black"), cex.points = 1.8, col = "red", prob = TRUE)
      hist(bootstrap_dist, prob = TRUE, breaks = 100, add = TRUE)
      # cat(paste0(d, "cm: ", "Norm(", round(Ex_bar, 2), ", ", round(se, 2), ")\n"))
      # cat("\n95% Confidence Interval: ", round(quantile(bootstrap_dist, c(0.025, 0.975)), 2), "\n")
      # cat(round(quantile(bootstrap_dist, c(0.025, 0.975)), 2), "\n")
      q <- round(quantile(bootstrap_dist, c(0.025, 0.975)), 2)
      abline(v = q, col = "skyblue")
      abline(v = median(bootstrap_dist), col = "skyblue")
      pandoc.p(paste0("\n95% Confidence Interval: (", q[1], "ms, ", q[2], "ms)"))

      means <- append(means, round(Ex_bar, 2))
      errors <- append(errors, round(se, 2))
      lower <- append(lower, q[1])
      higher <- append(higher, q[2])
    }
  }

  pandoc.header("Summary", level = 2)
  df <- data.frame(distances, means, errors, lower, higher)
  rownames(df) <- c("$\\beta_0$", "$\\beta_1$", "$\\beta_2$")
  # knitr::kable(df)
  pandoc.table(df, style = "grid", round = 2, digits = 6, justify = "rrrrrr")
  # pander(df)
}

```
