// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
Rcpp::List rcpp_hello_world();
RcppExport SEXP _memory_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// add
void add(Rcpp::RObject object);
RcppExport SEXP _memory_add(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type object(objectSEXP);
    add(object);
    return R_NilValue;
END_RCPP
}
// get
Rcpp::RObject get(std::size_t position);
RcppExport SEXP _memory_get(SEXP positionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type position(positionSEXP);
    rcpp_result_gen = Rcpp::wrap(get(position));
    return rcpp_result_gen;
END_RCPP
}
// reserve
void reserve(std::size_t new_cap);
RcppExport SEXP _memory_reserve(SEXP new_capSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type new_cap(new_capSEXP);
    reserve(new_cap);
    return R_NilValue;
END_RCPP
}
// clear
void clear();
RcppExport SEXP _memory_clear() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    clear();
    return R_NilValue;
END_RCPP
}
// size
std::size_t size();
RcppExport SEXP _memory_size() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(size());
    return rcpp_result_gen;
END_RCPP
}
// capacity
std::size_t capacity();
RcppExport SEXP _memory_capacity() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(capacity());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_type
void rcpp_type(Rcpp::RObject x);
RcppExport SEXP _memory_rcpp_type(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    rcpp_type(x);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_memory_rcpp_hello_world", (DL_FUNC) &_memory_rcpp_hello_world, 0},
    {"_memory_add", (DL_FUNC) &_memory_add, 1},
    {"_memory_get", (DL_FUNC) &_memory_get, 1},
    {"_memory_reserve", (DL_FUNC) &_memory_reserve, 1},
    {"_memory_clear", (DL_FUNC) &_memory_clear, 0},
    {"_memory_size", (DL_FUNC) &_memory_size, 0},
    {"_memory_capacity", (DL_FUNC) &_memory_capacity, 0},
    {"_memory_rcpp_type", (DL_FUNC) &_memory_rcpp_type, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_memory(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
