---
title: "R Notebook"
author: ferhat
date: 6.03.2021
output: html_document
---


```{r, echo = TRUE, message = FALSE}
set.seed(100)
library(SDS100)
library(distr)
```

```{r}
my_sample <- c(21, 29, 25, 19, 24, 22, 25, 26, 25, 29)

(x_bar <- mean(my_sample)) # original sample mean
(s <- sd(my_sample)) # standard deviation of the sample
n <- length(my_sample) # original sample size
hist(my_sample, breaks = 10) # histogram my sample

# number of bootstrap replicates = 10000
bootstrap_dist <- SDS100::do_it(10000) * {
  curr_boot <- sample(my_sample, n, replace = TRUE) # take bootstrap samples
  mean(curr_boot) # calculate bootstrap means
}
(se <- sd(bootstrap_dist)) # se (standard error) is sd of sampling distribution
(mb <- mean(bootstrap_dist)) # mean of the boot would be similar to sample mean
```
__Check that the bootstrap distribution is reasonably symmetric and bell-shaped.__
```{r}
hist(bootstrap_dist, breaks = 100)
abline(v = mb, col = "red")
abline(v = quantile(bootstrap_dist, c(0.005, 0.995)), col = "skyblue")

# Confidence intervals using quantiles
print("90% CI using quantiles")
(q <- round(quantile(bootstrap_dist, c(0.05, 0.95)), 2))
print("margin of error")
(me <- round(q[[2]] - mb, 2))

print("95% CI using quantiles")
(q <- round(quantile(bootstrap_dist, c(0.025, 0.975)), 2))
print("margin of error")
(me <- round(q[[2]] - mb, 2))

# inference of the population distribution
population_distr <- distr::Norm(x_bar, round(se, 2))
plot(population_distr, to.draw.arg = "d", bty = "7",
     panel.first = grid(lwd = 1), lwd = 1, vertical = FALSE,
     col.points = c("red", "black"), cex.points = 1.8, col = "red")
hist(bootstrap_dist, prob = TRUE, breaks = 100, add = TRUE)
```

addressing mode | 95% confidence interval         |  margin or error        | best estimate ($\mu$, $\sigma$) |
----------------|-----------------------------    |-------------------------|----------------------------|
000(MOV)        | (`r q[[1]]`, `r q[[2]]`)$\star$ |  `r x_bar` $\pm$ `r me` | Norm(`r x_bar`, `r round(se,2)`)|
001             | (..., ...)                      |  ...                    | Norm(..., ...)                  |
...             |                                 |                         |                                 |

$\star$ The margin of error is `r me`, and we are 95% confident (sure) that the
mean time for all "000" addressing mode instructions are between
`r q[[1]]` cycles and `r q[[2]]` cycles. To get more confidence that our interval
contains the true mean, we need to use a wider interval.

In general, we need to balance a reasonable chance of capturing the parameter of
interest with a need to narrow in on where the parameter might be. That is why
we commonly use confidence levels like 90%, 95%, or 99% depending on the
trade-off we are willing to make between a precise, narrow interval, and a good
chance that it succeeds.


Loop Overhead (50 samples, each sample runs 100,000 times, bootstrap 100,000)
```
Time @ 1 MHz (ns)
-----------------
Mode  Mean Sd
Loop  2310614078 45932124

Energy (uj)
-----------------
Mode  Mean Sd
Loop  3128.09 62.13
```

`Time @ 1 MHz (us)`

Mode| Mean | Sd   | Mean | Sd   |
----|:-----|:-----|:-----|:-----|
00 0| 1.54 | 0.46 | 1.54 | 0.46 |
00 1| 3.52 | 0.46 | 3.52 | 0.46 |
01 0| 3.50 | 0.46 | 3.50 | 0.46 |
01 1| 5.56 | 0.46 | 5.56 | 0.46 |
10 0| 2.55 | 0.46 | 2.55 | 0.46 |
10 1| 4.54 | 0.46 | 4.54 | 0.46 |
11 0| 2.54 | 0.46 | 2.54 | 0.46 |
11 1| 4.55 | 0.46 | 4.55 | 0.46 |

`Energy (nj)`

Mode| Mean Sd   |
----|-----------|
00 0| 2.07 0.62 |
00 1| 4.57 0.62 |
01 0| 4.44 0.62 |
01 1| 9.27 0.62 |
10 0| 3.37 0.62 |
10 1| 5.84 0.63 |
11 0| 3.08 0.62 |
11 1| 5.91 0.63 |

MOV
```
Time @ 1 MHz (us)
Mode  Mean Sd
00 0  1.24 0.46
00 1  3.2 0.46
01 0  3.31 0.46
01 1  5.27 0.46
10 0  2.21 0.46
10 1  4.22 0.46
11 0  2.25 0.46
11 1  4.26 0.46
Energy (nj)
Mode  Mean Sd
00 0  4.12 0.62
00 1  6.68 0.63
01 0  6.65 0.63
01 1  9.77 0.63
10 0  5.43 0.63
10 1  7.99 0.64
11 0  5.14 0.62
11 1  8.01 0.6
```

ADD
```
Time @ 1 MHz (us)
Mode  Mean Sd
00 0  4.7 0.71
00 1  2.87 0.51
01 0  4.7 0.52
01 1  3.35 0.67
10 0  4.49 0.56
10 1  2.23 0.63
11 0  3.51 0.53
11 1  3.87 0.5
Energy (nj)
Mode  Mean Sd
00 0  9.31 1.3
00 1  5.62 0.77
01 0  9.26 0.73
01 1  5.66 1.49
10 0  9.46 0.83
10 1  3.49 1.21
11 0  5.57 0.81
11 1  7.74 0.9
```