# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_memory_rcpp_hello_world`)
}

add <- function(object) {
    invisible(.Call(`_memory_add`, object))
}

get <- function(position) {
    .Call(`_memory_get`, position)
}

reserve <- function(new_cap) {
    invisible(.Call(`_memory_reserve`, new_cap))
}

clear <- function() {
    invisible(.Call(`_memory_clear`))
}

size <- function() {
    .Call(`_memory_size`)
}

capacity <- function() {
    .Call(`_memory_capacity`)
}

rcpp_type <- function(x) {
    invisible(.Call(`_memory_rcpp_type`, x))
}

